### ISSUE TITLE
Is AD management possible ?

### ISSUE THREAD

**Issue by lightsabata** [shiroinekotfs/WAC-on-DC#1]
Hi !
I’ve just discovered your repo and i wonder if with this method, you can bypass microsoft rule and manage the AD with WAC installed on the host

thank you

**Comment by shiroinekotfs** [comment]
The Active Directory and the entire infrastructure may get destroyed by just installing WAC on any domain controller.

Thanks for your reminder, I will update the repo by archiving it, not active, to follow [Microsoft recommendations of security on Active Directory infrastructure ](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/plan/installation-options).

> Installing Windows Admin Center on a Domain controller is not supported. Read more about domain controller security best practices.
